//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace IINACT.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool RPcap {
            get {
                return ((bool)(this["RPcap"]));
            }
            set {
                this["RPcap"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int ParseFilterMode {
            get {
                return ((int)(this["ParseFilterMode"]));
            }
            set {
                this["ParseFilterMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DisableDamageShield {
            get {
                return ((bool)(this["DisableDamageShield"]));
            }
            set {
                this["DisableDamageShield"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DisableCombinePets {
            get {
                return ((bool)(this["DisableCombinePets"]));
            }
            set {
                this["DisableCombinePets"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SimulateIndividualDoTCrits {
            get {
                return ((bool)(this["SimulateIndividualDoTCrits"]));
            }
            set {
                this["SimulateIndividualDoTCrits"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowRealDoTTicks {
            get {
                return ((bool)(this["ShowRealDoTTicks"]));
            }
            set {
                this["ShowRealDoTTicks"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowDebug {
            get {
                return ((bool)(this["ShowDebug"]));
            }
            set {
                this["ShowDebug"] = value;
            }
        }
    }
}
