//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowMage.OverlayPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainbowMage.OverlayPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTWS compatibility shim enabled..
        /// </summary>
        internal static string ActwsShimEnabled {
            get {
                return ResourceManager.GetString("ActwsShimEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomPresetLabel {
            get {
                return ResourceManager.GetString("CustomPresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate handler for name {0}!.
        /// </summary>
        internal static string DuplicateHandlerError {
            get {
                return ResourceManager.GetString("DuplicateHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewOverlayDialog: Failed to load presets: {0}.
        /// </summary>
        internal static string ErrorCouldNotLoadPresets {
            get {
                return ResourceManager.GetString("ErrorCouldNotLoadPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be empty or white space only..
        /// </summary>
        internal static string ErrorOverlayNameEmpty {
            get {
                return ResourceManager.GetString("ErrorOverlayNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be unique..
        /// </summary>
        internal static string ErrorOverlayNameNotUnique {
            get {
                return ResourceManager.GetString("ErrorOverlayNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Settings.
        /// </summary>
        internal static string EventConfigTab {
            get {
                return ResourceManager.GetString("EventConfigTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to dispatch event {0} to {1}! {2}.
        /// </summary>
        internal static string EventHandlerException {
            get {
                return ResourceManager.GetString("EventHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the FFXIV DataRepository: {0}.
        /// </summary>
        internal static string FFXIVDataRepositoryException {
            get {
                return ResourceManager.GetString("FFXIVDataRepositoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the FFXIV DataSubscription: {0}.
        /// </summary>
        internal static string FFXIVDataSubscriptionException {
            get {
                return ResourceManager.GetString("FFXIVDataSubscriptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle clickthrough.
        /// </summary>
        internal static string HotkeyActionToggleClickthrough {
            get {
                return ResourceManager.GetString("HotkeyActionToggleClickthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle enabled.
        /// </summary>
        internal static string HotkeyActionToggleEnabled {
            get {
                return ResourceManager.GetString("HotkeyActionToggleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle lock.
        /// </summary>
        internal static string HotkeyActionToggleLock {
            get {
                return ResourceManager.GetString("HotkeyActionToggleLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle visible/hide.
        /// </summary>
        internal static string HotkeyActionToggleVisible {
            get {
                return ResourceManager.GetString("HotkeyActionToggleVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected incompatible addon {0}. Please update as soon as possible!!.
        /// </summary>
        internal static string IncompatibleAddon {
            get {
                return ResourceManager.GetString("IncompatibleAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeOverlay: Local file {0} does not exist!.
        /// </summary>
        internal static string InitOverlayLocalFileIsMissing {
            get {
                return ResourceManager.GetString("InitOverlayLocalFileIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeOverlay: URI parse error! Please reconfigure the URL. (Config.Url = {0}): {1}.
        /// </summary>
        internal static string InitOverlayUrlError {
            get {
                return ResourceManager.GetString("InitOverlayUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JS Handler call failed: {0}.
        /// </summary>
        internal static string JsHandlerCallException {
            get {
                return ResourceManager.GetString("JsHandlerCallException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sort list by {0}: {1}.
        /// </summary>
        internal static string ListSortFailed {
            get {
                return ResourceManager.GetString("ListSortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Log not connected..
        /// </summary>
        internal static string LogNotConnectedError {
            get {
                return ResourceManager.GetString("LogNotConnectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniParseEventSource.
        /// </summary>
        internal static string MapESMiniParse {
            get {
                return ResourceManager.GetString("MapESMiniParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelOverlay.
        /// </summary>
        internal static string MapOverlayLabel {
            get {
                return ResourceManager.GetString("MapOverlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniParseOverlay.
        /// </summary>
        internal static string MapOverlayMiniParse {
            get {
                return ResourceManager.GetString("MapOverlayMiniParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string MapOverlayShortLabel {
            get {
                return ResourceManager.GetString("MapOverlayShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniParse.
        /// </summary>
        internal static string MapOverlayShortMiniParse {
            get {
                return ResourceManager.GetString("MapOverlayShortMiniParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpellTimer.
        /// </summary>
        internal static string MapOverlayShortSpellTimer {
            get {
                return ResourceManager.GetString("MapOverlayShortSpellTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpellTimerOverlay.
        /// </summary>
        internal static string MapOverlaySpellTimer {
            get {
                return ResourceManager.GetString("MapOverlaySpellTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to dispatch unregistered event type &quot;{0}&quot;!.
        /// </summary>
        internal static string MissingEventDispatchError {
            get {
                return ResourceManager.GetString("MissingEventDispatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got a subscription for missing event &quot;{0}&quot;!.
        /// </summary>
        internal static string MissingEventSubError {
            get {
                return ResourceManager.GetString("MissingEventSubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to call missing handler &quot;{0}&quot;!.
        /// </summary>
        internal static string MissingHandlerError {
            get {
                return ResourceManager.GetString("MissingHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setup network parser: {0}.
        /// </summary>
        internal static string NetworkParserInitException {
            get {
                return ResourceManager.GetString("NetworkParserInitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Machina or the FFXIV plugin. This is only an issue if you&apos;re using ACT with FFXIV..
        /// </summary>
        internal static string NetworkParserNoFfxiv {
            get {
                return ResourceManager.GetString("NetworkParserNoFfxiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid handler call: {0}.
        /// </summary>
        internal static string OverlayApiInvalidHandlerCall {
            get {
                return ResourceManager.GetString("OverlayApiInvalidHandlerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing events field in subscribe call: {0}!.
        /// </summary>
        internal static string OverlayApiMissingEventsField {
            get {
                return ResourceManager.GetString("OverlayApiMissingEventsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing events field in unsubscribe call: {0}!.
        /// </summary>
        internal static string OverlayApiMissingEventsFieldUnsub {
            get {
                return ResourceManager.GetString("OverlayApiMissingEventsFieldUnsub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Subscribed to {1}.
        /// </summary>
        internal static string OverlayApiSubscribed {
            get {
                return ResourceManager.GetString("OverlayApiSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey: {0}!.
        /// </summary>
        internal static string OverlayBaseRegisterHotkeyError {
            get {
                return ResourceManager.GetString("OverlayBaseRegisterHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string OverlayPreviewName {
            get {
                return ResourceManager.GetString("OverlayPreviewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset {0} uses unsupported type {1}!.
        /// </summary>
        internal static string PresetUsesUnsupportedType {
            get {
                return ResourceManager.GetString("PresetUsesUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select overlay type..
        /// </summary>
        internal static string PromptSelectOverlayType {
            get {
                return ResourceManager.GetString("PromptSelectOverlayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a preset..
        /// </summary>
        internal static string PromptSelectPreset {
            get {
                return ResourceManager.GetString("PromptSelectPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey {0}, {1} in EnableHotKeys()..
        /// </summary>
        internal static string RegisterHotkeyError {
            get {
                return ResourceManager.GetString("RegisterHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Source.
        /// </summary>
        internal static string TabsESLabel {
            get {
                return ResourceManager.GetString("TabsESLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unregister hotkey {0} in DisableHotKeys()..
        /// </summary>
        internal static string UnregisterHotkeyError {
            get {
                return ResourceManager.GetString("UnregisterHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS: Handler call failed: {0}.
        /// </summary>
        internal static string WSHandlerException {
            get {
                return ResourceManager.GetString("WSHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;It Works!&lt;/h1&gt;
        ///        &lt;p&gt;
        ///            If any of these links are displayed with a &amp;quot;Local:&amp;quot; prefix and not clickable then that&apos;s because
        ///            those overlays display local files and web browsers don&apos;t allow web sites to link to local files.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            You&apos;ll have to copy &amp;amp; paste that link into your address bar.
        ///        &lt;/p&gt;.
        /// </summary>
        internal static string WSIndexPage {
            get {
                return ResourceManager.GetString("WSIndexPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data received: {0}; {1}.
        /// </summary>
        internal static string WSInvalidDataRecv {
            get {
                return ResourceManager.GetString("WSInvalidDataRecv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS: Loading SSL certificate {0}....
        /// </summary>
        internal static string WSLoadingCert {
            get {
                return ResourceManager.GetString("WSLoadingCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send message: {0}.
        /// </summary>
        internal static string WSMessageSendFailed {
            get {
                return ResourceManager.GetString("WSMessageSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process new subscription: {0}.
        /// </summary>
        internal static string WSNewSubFail {
            get {
                return ResourceManager.GetString("WSNewSubFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link might not work if the overlay doesn&apos;t support ACTWebSocket..
        /// </summary>
        internal static string WSNotConfidentLink {
            get {
                return ResourceManager.GetString("WSNotConfidentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS: Failed to shutdown. {0}.
        /// </summary>
        internal static string WSShutdownError {
            get {
                return ResourceManager.GetString("WSShutdownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS: Failed to start: {0}.
        /// </summary>
        internal static string WSStartFailed {
            get {
                return ResourceManager.GetString("WSStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process unsubscription: {0}.
        /// </summary>
        internal static string WSUnsubFail {
            get {
                return ResourceManager.GetString("WSUnsubFail", resourceCulture);
            }
        }
    }
}
